### ISSUE TITLE
No module named 'hshadow'

### ISSUE THREAD

**Issue by shaopingLL** [ShengCN/PixHtLab-Src#16]
I want to run the PixHtLab-Demo, Demo/PixhtLab/Demo.ipynb. But when I run this jupyter file, it shows that 'No module named 'hshadow'', and I think 'hshadow' maybe a tool module that you composed. But after I checked the folder  'Demo/PixhtLab/', I haven't find the file named like 'hshadow.py'. My issue is whether this module is necessary and if it were necessary, can you supply this file and I'll be grateful to you.

**Comment by ShengCN** [comment]
Hi, I guess the environment is not correctly setup. hshadow is a module you need to compile in your python environment. You can take a look at L8 in env.sh file, there is a Torch_Render folder under `Demo/PixhtLab/Torch_Render`. You can install the module using this command:

`cd Demo/PixhtLab/Torch_Render && pip install . && cd - && echo "Torch Render Installed"`

**Comment by shaopingLL** [comment]
收到

**Comment by shaopingLL** [comment]
Thanks for your help, I find this problem is caused by the torch version not matching the cuda version of my server and I upgrade my torch and successfully compile it.

**Comment by LukaGiorgadze** [comment]
@shaopingLL Did you run the demo? I tried but getting this error https://github.com/ShengCN/PixHtLab-Src/issues/20

**Comment by shaopingLL** [comment]
收到
