### ISSUE TITLE
pretrained weights

### ISSUE THREAD

**Issue by smohammadi96** [ShengCN/PixHtLab-Src#17]
Hello,
Pretrained models are available or not?
`model = inference_shadow.init_models('/home/ysheng/Documents/Research/GSSN/HardShadow/qtGUI/weights/human_baseline_all_21-July-04-52-AM.pt') `

`GSSN_model = SSN_Infernece('/home/ysheng/Documents/Research/GSSN/HardShadow/qtGUI/GSSN/weights/only_shadow/0000000200.pt')`

**Comment by lxztju** [comment]
@ShengCN  Is the pretrained weights available?

**Comment by ShengCN** [comment]
Here is the Dropbox link: human_baseline_all_21-July-04-52-AM.pt https://www.dropbox.com/scl/fi/7vzb0hlff0wbbb6l6qiyb/human_baseline_all_21-July-04-52-AM.pt\?rlkey\=lw34u1qao6had58t9vqy3bfbj\&dl\=0.

**Comment by SriramGS** [comment]
Are the weights mentioned [here](https://github.com/ShengCN/PixHtLab-Src/blob/a4743f68f35f45194c6cb574f96f0615f543a197/Demo/PixhtLab/hshadow_render.py#L18) available as well. - `/home/ysheng/Documents/Research/GSSN/HardShadow/qtGUI/GSSN/weights/only_shadow/0000000200.pt`

**Comment by smohammadi96** [comment]
> Are the weights mentioned [here](https://github.com/ShengCN/PixHtLab-Src/blob/a4743f68f35f45194c6cb574f96f0615f543a197/Demo/PixhtLab/hshadow_render.py#L18) available as well. - `/home/ysheng/Documents/Research/GSSN/HardShadow/qtGUI/GSSN/weights/only_shadow/0000000200.pt`

They are not available!!

**Comment by smohammadi96** [comment]
> Here is the Dropbox link: human_baseline_all_21-July-04-52-AM.pt [https://www.dropbox.com/scl/fi/7vzb0hlff0wbbb6l6qiyb/human_baseline_all_21-July-04-52-AM.pt\?rlkey\=lw34u1qao6had58t9vqy3bfbj\&dl\=0](https://www.dropbox.com/scl/fi/7vzb0hlff0wbbb6l6qiyb/human_baseline_all_21-July-04-52-AM.pt%5C?rlkey%5C=lw34u1qao6had58t9vqy3bfbj%5C&dl%5C=0).

Thanks.

**Comment by SriramGS** [comment]
Thanks for the quick reply @smohammadi96 . Any suggestions for alternatives ways to get the weights file.

**Comment by ShengCN** [comment]
> Thanks for the quick reply @smohammadi96 . Any suggestions for alternatives ways to get the weights file.

See this link: https://www.dropbox.com/scl/fi/7vzb0hlff0wbbb6l6qiyb/human_baseline_all_21-July-04-52-AM.pt?rlkey=lw34u1qao6had58t9vqy3bfbj&dl=0

**Comment by smohammadi96** [comment]
> > Thanks for the quick reply @smohammadi96 . Any suggestions for alternatives ways to get the weights file.
> 
> See this link: https://www.dropbox.com/scl/fi/7vzb0hlff0wbbb6l6qiyb/human_baseline_all_21-July-04-52-AM.pt?rlkey=lw34u1qao6had58t9vqy3bfbj&dl=0

GSSN is another weight for shadow generation.
https://github.com/ShengCN/PixHtLab-Src/blob/main/Demo/PixhtLab/hshadow_render.py (**Line 18**)
