### ISSUE TITLE
help: how can I run the `PixHtLab` demo for a given bg/fg pair?

### ISSUE THREAD

**Issue by mehamednews** [ShengCN/PixHtLab-Src#19]

**Comment by mehamednews** [comment]
this is the provided demo result:
![image](https://github.com/ShengCN/PixHtLab-Src/assets/53986586/0bc9712b-cbf4-4b44-a513-32e7c191ee3b)

these are the 2 mask/depth files I'm trying to generate for my images:
![image](https://github.com/ShengCN/PixHtLab-Src/assets/53986586/06a54339-0b37-4607-b214-acc4dbbfa7f6)
![image](https://github.com/ShengCN/PixHtLab-Src/assets/53986586/5d0c3454-c4e9-43e0-a533-b55e3e58dbaf)

**Comment by LukaGiorgadze** [comment]
@mehamednews Did you run it? I tried but getting this error https://github.com/ShengCN/PixHtLab-Src/issues/20

**Comment by mehamednews** [comment]
@LukaGiorgadze I too got this error
here's the list of changes I made to get this to work
![image](https://github.com/ShengCN/PixHtLab-Src/assets/53986586/2e137ddb-90e7-4781-9dad-983438ba0b19)
![image](https://github.com/ShengCN/PixHtLab-Src/assets/53986586/84415136-804f-4d2c-948c-75e38ec4435f)
![image](https://github.com/ShengCN/PixHtLab-Src/assets/53986586/6c977933-21d0-4465-9109-e0debad7777c)
