### ISSUE TITLE
Code release time estimate

### ISSUE THREAD

**Issue by lefreud** [ShengCN/PixHtLab-Src#3]
First of all, thank you for publishing these two interesting papers about pixel height @ShengCN and all of the team !

I was wondering if you have an estimate on the moment the inference code/model will be made available? I would love to be able to use this in my research project without having to re-implement and re-train the model myself. If you don't think these will be made available in the near future, I would also like to know 🙂, so I can plan accordingly.

I see that there is a [Demo](https://github.com/ShengCN/PixHtLab-Src/tree/Demo) branch, but it doesn't seem to be documented yet and hasn't been merged.

Thank you and have a great day!

**Comment by bmvd70** [comment]
Hi, I'd like to join lefreud on this: The paper is really interesting and I would also like to branch my research in this direction.

**Comment by cccpocker** [comment]
ready to code release!

**Comment by ShengCN** [comment]
@lefreud @bmvd70 @cccpocker Thank you for your interest and for your patience. The SSN code is ready. I am working on preparing the SSG/PixHtLab codes/demos/data ready soon. It is expected to be done in days.

**Comment by bonlime** [comment]
@ShengCN Hi! could you give any estimates on when you would finally release it?

**Comment by ShengCN** [comment]
@bonlime @cccpocker @bmvd70 @lefreud  The code has been released. Take a look!
