### ISSUE TITLE
dependent of imagen library

### ISSUE THREAD

**Issue by qzq2514** [ShengCN/PixHtLab-Src#5]
Nice work, but when i run training of ssn, some errors always happen because of "imagen",could you offer complete library of imagen or give some instruction about it? I will realy appreciate your help

**Comment by ShengCN** [comment]
Hi, imagen is from this repo: https://github.com/holoviz-topics/imagen. Cloning this repo, and call pip install . inside this repo to install this package. 

I will make an update on the README about how to configure environment.
